#!/usr/bin/env bash
# create_skill.sh – Scaffold a new OpenClaw skill.
# Usage: create_skill.sh <skill-name>
# Example: create_skill.sh my-awesome-tool

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <skill-name>" >&2
  exit 1
fi

NAME="$1"
# Sanitize name: lower‑case, alphanum, hyphens/underscores only
SAFE_NAME=$(echo "$NAME" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9_-]+/-/g' | sed -E 's/^-+|\-+$//g')

SKILL_DIR="~/.openclaw/workspace/skills/${SAFE_NAME}"
mkdir -p "$SKILL_DIR"

# Create a basic SKILL.md
cat > "${SKILL_DIR}/SKILL.md" <<'EOF'
# SKILL.md - <Skill Name>

## Description

A short description of what this skill does.

## Usage

Explain how to invoke the skill, required tools, and any configuration.

## Implementation Notes

- List any external dependencies.
- Mention any required permissions.

## License

MIT or appropriate license.
EOF

# Create a placeholder index file (could be a JS/TS module or a bash script)
cat > "${SKILL_DIR}/index.js" <<'EOF'
// Entry point for the skill – export any functions or classes needed by OpenClaw.
module.exports = {
  // Example function
  hello: () => console.log('Hello from ${SAFE_NAME}!'),
};
EOF

# Add a README for developers
cat > "${SKILL_DIR}/README.md" <<'EOF'
# ${SAFE_NAME} Skill

This skill was generated by `create_skill.sh`.

- Edit `SKILL.md` to describe the skill.
- Implement the logic in `index.js` (or another language as needed).
- Run `openclaw skill reload` or restart the gateway to pick up changes.
EOF

echo "Skill scaffold created at $SKILL_DIR"
